In [1]:
import pandas as pd
import numpy as np

In [2]:
n = np.random.randint(100)
n

41

In [4]:
n = np.random.rand()
n

0.4460659618099999

In [5]:
array = np.random.randint(100, size=(3))
array

array([16, 33, 73], dtype=int32)

In [6]:
array = np.random.randint(100, size=(3,3))
array

array([[45, 61, 86],
       [43, 12, 51],
       [14,  1, 17]], dtype=int32)

In [8]:
array = np.random.rand(3)
array

array([0.80954587, 0.275336  , 0.23826585])

In [9]:
array = np.random.rand(3,2)
array

array([[0.03522351, 0.2085867 ],
       [0.32327583, 0.29659408],
       [0.26767444, 0.28557027]])

In [10]:
c = np.random.choice([1,2,3,4])
c

np.int64(4)

In [11]:
c = np.random.choice([1,2,3,4], size=(2,2))
c

array([[1, 4],
       [4, 3]])

In [13]:
array = np.random.choice([1,3,5,7], p=[0.1,0.2,0.3,0.4], size=(100))
array

array([5, 5, 7, 7, 5, 3, 3, 5, 7, 3, 3, 5, 1, 7, 7, 5, 3, 3, 3, 7, 1, 5,
       5, 1, 3, 3, 5, 5, 1, 7, 7, 7, 5, 5, 5, 7, 5, 7, 5, 7, 5, 5, 7, 7,
       5, 5, 1, 3, 5, 5, 7, 3, 3, 7, 7, 5, 5, 7, 7, 3, 7, 7, 7, 3, 5, 5,
       5, 7, 7, 5, 5, 5, 7, 5, 7, 7, 5, 7, 3, 3, 3, 5, 3, 7, 7, 7, 5, 7,
       5, 5, 5, 7, 1, 5, 1, 7, 5, 5, 7, 5])

In [17]:
arary = np.random.choice([1,3,5,7], p=[0.0, 0.1, 0.3,0.6], size=(2,3))
arary

array([[5, 5, 7],
       [3, 7, 7]])

In [19]:
array = np.random.randint(100, size=(5))
array

array([83, 11, 90, 82, 16], dtype=int32)

In [20]:
np.random.shuffle(array)
array

array([83, 90, 11, 82, 16], dtype=int32)

In [21]:
array = np.random.randint(100, size=(5))
array

array([87, 87, 50, 62, 85], dtype=int32)

In [24]:
new_array = np.random.permutation(array)
array, new_array

(array([87, 85, 50, 87, 62], dtype=int32),
 array([85, 50, 87, 87, 62], dtype=int32))

In [25]:
normal_dist = np.random.normal(size=(3,2))
normal_dist

array([[-0.81836082,  2.09846767],
       [-0.2956469 ,  0.62071184],
       [ 0.12566688,  1.26358421]])

In [26]:
normal_dist = np.random.normal(loc=1, scale=2, size=(3,3))
normal_dist

array([[ 1.85584101,  1.88357978,  2.87853741],
       [-0.70867557, -0.05420194,  3.24318136],
       [-0.42340708,  1.04847183,  2.33030055]])

In [30]:
binomial_dist = np.random.binomial(n=10, p=0.5, size=10)
binomial_dist

array([7, 6, 7, 4, 4, 5, 4, 2, 7, 5], dtype=int32)

In [33]:
poission_dist = np.random.poisson(lam=2, size=10)
poission_dist

array([1, 1, 1, 6, 2, 0, 1, 0, 1, 3], dtype=int32)

In [34]:
uniform_dist = np.random.uniform(size=(20))
uniform_dist

array([0.8030389 , 0.81224563, 0.12566501, 0.13336683, 0.5697483 ,
       0.30515447, 0.37958944, 0.50794462, 0.97124876, 0.28229091,
       0.88274883, 0.60863548, 0.68447539, 0.98875028, 0.40005411,
       0.21667205, 0.28698935, 0.45772475, 0.90695756, 0.39926141])

In [36]:
logistic_dist = np.random.logistic(loc=1, scale=2, size=(2, 3))
logistic_dist

array([[-0.80702693,  0.45784588,  3.37399102],
       [ 4.94640561,  4.57034535,  1.40752655]])

In [37]:
multi_dist = np.random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
multi_dist

array([0, 2, 2, 0, 2, 0], dtype=int32)

In [39]:
exp_dist = np.random.exponential(scale=2, size=(2, 3))
exp_dist

array([[ 2.90992444,  0.98251197, 12.44621942],
       [ 0.53912551,  1.21360825,  3.52363052]])

In [40]:
chi_dist = np.random.chisquare(df=2, size=(2, 3))
chi_dist

array([[1.15399676, 0.89496785, 3.29227719],
       [3.087819  , 8.1678326 , 1.03533562]])

In [41]:
ray_dist = np.random.rayleigh(scale=2, size=(2, 3))
ray_dist

array([[2.6027754 , 5.64604477, 3.28091785],
       [3.38130783, 2.89879959, 2.31435308]])

In [42]:
par_dist = np.random.pareto(a=2, size=(2, 3))
par_dist

array([[1.21376378, 0.80876976, 0.14260748],
       [0.21571362, 0.15827836, 0.20535569]])

In [43]:
zip_dist = np.random.zipf(a=2, size=(2, 3))
zip_dist

array([[1, 1, 1],
       [2, 1, 1]], dtype=int32)

In [44]:
np.array([1,1.2, True, 'ada'])

array(['1', '1.2', 'True', 'ada'], dtype='<U32')